#!/bin/bash
set -e

DB_PASSWORD=$(cat /storage/config/.db_password)

echo "Dumping WordPress database..."
mysqldump -u wordpress -p"${DB_PASSWORD}" wordpress > /storage/db/database.sql

echo "Backup prepared."
